### PR TITLE
feat: added button component page and css

### PR DESCRIPTION
**Pull request by zabihshaik**
Added Button Component Page and CSS files and imported the button.css file into main.css.

Button Page looks like:

Button Page

Deploy Preview Link:
https://deploy-preview-4--neoz-ui.netlify.app/pages/button.html

### CODE REVIEW

**Review by bharati-21 — APPROVED** [review]
Looks good to be merged. Neat and understandable code!

**Review by NeerajVodala — APPROVED** [review]
Looks good to me.
All the best

**Comment by TejasShekar** [comment]
Looks good to merge !

**Review by TejasShekar — APPROVED** [review]
Looks good to merge

**Pull request merged**
