### PR TITLE
feat: added Navigation Component & updated it's link in other pages

### PR DESCRIPTION
**Pull request by zabihshaik**
Added Navigation Component & updated it's link in other pages.

Navigation Page looks like:

Navigation Page

Deploy Preview Link:

https://deploy-preview-8--neoz-ui.netlify.app/pages/navigation.html

### CODE REVIEW

**Review by bharati-21 — APPROVED** [review]
Looks good to be merged!

**Comment by agrawalshanu708** [comment]
Try to give space between main paragraph and h2, it would looks better and else is looking good

**Comment by agrawalshanu708** [comment]
Better to give space between main paragraph and sub heading it would looks better

**Review by agrawalshanu708 — APPROVED** [review]
it looks good to merge, but you can add some bottom margin to main paragraph

**Pull request merged**
